/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "./stencil-public-runtime";
export namespace Components {
    interface RarSideDrawer {
        "opened": boolean;
        "title": string;
    }
    interface RarSpinner {
    }
    interface RarStockFinder {
    }
    interface RarStockPrice {
        "stockSymbolProp": string;
    }
    interface RarTooltip {
        "opened": boolean;
        "text": string;
    }
}
declare global {
    interface HTMLRarSideDrawerElement extends Components.RarSideDrawer, HTMLStencilElement {
    }
    var HTMLRarSideDrawerElement: {
        prototype: HTMLRarSideDrawerElement;
        new (): HTMLRarSideDrawerElement;
    };
    interface HTMLRarSpinnerElement extends Components.RarSpinner, HTMLStencilElement {
    }
    var HTMLRarSpinnerElement: {
        prototype: HTMLRarSpinnerElement;
        new (): HTMLRarSpinnerElement;
    };
    interface HTMLRarStockFinderElement extends Components.RarStockFinder, HTMLStencilElement {
    }
    var HTMLRarStockFinderElement: {
        prototype: HTMLRarStockFinderElement;
        new (): HTMLRarStockFinderElement;
    };
    interface HTMLRarStockPriceElement extends Components.RarStockPrice, HTMLStencilElement {
    }
    var HTMLRarStockPriceElement: {
        prototype: HTMLRarStockPriceElement;
        new (): HTMLRarStockPriceElement;
    };
    interface HTMLRarTooltipElement extends Components.RarTooltip, HTMLStencilElement {
    }
    var HTMLRarTooltipElement: {
        prototype: HTMLRarTooltipElement;
        new (): HTMLRarTooltipElement;
    };
    interface HTMLElementTagNameMap {
        "rar-side-drawer": HTMLRarSideDrawerElement;
        "rar-spinner": HTMLRarSpinnerElement;
        "rar-stock-finder": HTMLRarStockFinderElement;
        "rar-stock-price": HTMLRarStockPriceElement;
        "rar-tooltip": HTMLRarTooltipElement;
    }
}
declare namespace LocalJSX {
    interface RarSideDrawer {
        "onCloseDrawer"?: (event: CustomEvent<void>) => void;
        "opened"?: boolean;
        "title"?: string;
    }
    interface RarSpinner {
    }
    interface RarStockFinder {
        "onSymbolSelected"?: (event: CustomEvent<string>) => void;
    }
    interface RarStockPrice {
        "stockSymbolProp"?: string;
    }
    interface RarTooltip {
        "opened"?: boolean;
        "text"?: string;
    }
    interface IntrinsicElements {
        "rar-side-drawer": RarSideDrawer;
        "rar-spinner": RarSpinner;
        "rar-stock-finder": RarStockFinder;
        "rar-stock-price": RarStockPrice;
        "rar-tooltip": RarTooltip;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "rar-side-drawer": LocalJSX.RarSideDrawer & JSXBase.HTMLAttributes<HTMLRarSideDrawerElement>;
            "rar-spinner": LocalJSX.RarSpinner & JSXBase.HTMLAttributes<HTMLRarSpinnerElement>;
            "rar-stock-finder": LocalJSX.RarStockFinder & JSXBase.HTMLAttributes<HTMLRarStockFinderElement>;
            "rar-stock-price": LocalJSX.RarStockPrice & JSXBase.HTMLAttributes<HTMLRarStockPriceElement>;
            "rar-tooltip": LocalJSX.RarTooltip & JSXBase.HTMLAttributes<HTMLRarTooltipElement>;
        }
    }
}
